# Generated by Django 5.0.7 on 2024-07-31 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_image_alter_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
